### ISSUE TITLE
ClassNotFoundException in AppKernel.php

### ISSUE THREAD

**Issue by karthikajjan** [mcfedr/awspushbundle#11]
Hi,

Installed mcfedr/awspushbundle V5.1.2 (version), but I got error while include awspushbundle in appkernel. Plz refer below screenshots:

1. Installed path:
![screen1](https://cloud.githubusercontent.com/assets/4723648/17268528/52bb31e2-564a-11e6-9334-0dbf591a8101.png)

2. Include in appkernel:
![screen2](https://cloud.githubusercontent.com/assets/4723648/17268530/59209810-564a-11e6-83ba-d66efcb22462.png)

3.Error:
![screen3](https://cloud.githubusercontent.com/assets/4723648/17268531/5ce6e008-564a-11e6-9a5a-d8117f329bd9.png)

Thanks

**Comment by mcfedr** [comment]
Looks like a autoloading problem, maybe you need to update your composer?

**Comment by karthikajjan** [comment]
Exactly it autoloading problem, delete bundle in vendor folder and then install once again.
Thanks @mcfedr.
