### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by panslaw** [mcfedr/awspushbundle#20]
I have error when I try installing plugin:

Notice: Undefined index: platforms In McfedrAwsPushExtension.php line 28:

**Comment by Kyngo** [comment]
So do I, anyone willing to help here?

**Comment by mcfedr** [comment]
You probably need to add the configuration, as in the readme. The bundle
doesn't currently have autoconfig for symfony 4 style.

**Comment by mcfedr** [comment]
I've added a flex receipe that will now create a default config
