### ISSUE TITLE
Device disabled error

### ISSUE THREAD

**Issue by simonvollmer** [mcfedr/awspushbundle#22]
If a device is disabled in SNS, an error is thrown preventing the rest of my code from functioning – can't seem to find a method to check if a device is enabled prior to delivery of method therefore I can't guarantee execution of the rest of my code, what's the normal approach to handle this?

**Comment by mcfedr** [comment]
I'd recommend you catch the error, and handle it appropriately - you might for example mark it in your own database as being disabled.
