### ISSUE TITLE
APNS aps data

### ISSUE THREAD

**Issue by Mijail** [mcfedr/awspushbundle#8]
I can't find any way to set aps data except badge, sound and content-avaliable. 

How can I set category for example?

I found on your documentation the customAPNSdata but it seems it encapsulates it outside the aps key.

Could you provide a method to add an array of data the user wants inside aps key?

Thank you!

**Comment by mcfedr** [comment]
The custom data is deep merged with the data set via other properties, this means you can do something like

    $message->setApnsData(['aps' => ['category' => 'Some category']]);

**Comment by Mijail** [comment]
Oh thats awesome. Sorry about that.

Thanks!

**Comment by mcfedr** [comment]
Added documentation to the `set` methods of Message that should make this clearer, 6.5.1 release
https://github.com/mcfedr/awspushbundle/commit/baf3883223591457d989e00670d69512ba131a4b
