### ISSUE TITLE
Microsoft Platforms(WNS,MPNS)

### ISSUE THREAD

**Issue by yusufiga** [mcfedr/awspushbundle#9]
Hi,

First of all thank you for your great work. I have a question. Can you add the Windows Phone push platforms or can you help me how can I add them to your bundle.

Thanks.

**Comment by mcfedr** [comment]
I guess you worked it out?

**Comment by yusufiga** [comment]
Actualy I haven't try it yet. But it looks like your code already has this
feature as far as I saw.

On Monday, 2 May 2016, Fred Cox <notifications@github.com> wrote:

> I guess you worked it out?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/mcfedr/awspushbundle/issues/9#issuecomment-216344454>
>


-- 
iPhone'umdan gönderildi

**Comment by mcfedr** [comment]
I have never used WNS or MPNS, but as most of the code is platform independent it should work when you provide the correct ARN. There might be some specifics that are missing, much as maximum message length and collapse keys, these are handled for GCM and ADM. Feel free to open issues or pull requests if and when you find these things.
